version: '3'
services:
  service_jekyll:
    image: jekyll/jekyll:4.1.0
    container_name: local_jekyll
    volumes:
      - .:/srv/jekyll
    command: jekyll serve --watch
    ports:
      - 4000:4000
